### ISSUE TITLE
Diagram1

### ISSUE THREAD

**Issue by Nadapotata** [NCBI-Hackathons/deSRA#1]
https://files.slack.com/files-pri/T7QHB9VUG-F7WCF11PW/info-flow.jpg

**Comment by Nadapotata** [comment]
![info-flow](https://user-images.githubusercontent.com/12971527/32506375-62c19028-c3b2-11e7-9377-848b3e50016e.jpg)

**Comment by Nadapotata** [comment]
![image](https://user-images.githubusercontent.com/12971527/32507410-558dd864-c3b5-11e7-9ac7-a038164de797.png)

**Comment by Nadapotata** [comment]
![image](https://user-images.githubusercontent.com/12971527/32507427-6280a0ba-c3b5-11e7-8ecb-d24365631596.png)

**Comment by Nadapotata** [comment]
![image](https://user-images.githubusercontent.com/12971527/32507439-6a004156-c3b5-11e7-8298-ced875e54c36.png)

**Comment by Nadapotata** [comment]
![input page exp1](https://user-images.githubusercontent.com/12971527/32568276-c0a25ab8-c48b-11e7-8143-08cebecc6b1c.png)

**Comment by Nadapotata** [comment]
![image](https://user-images.githubusercontent.com/12971527/32574712-ff0dbfb8-c49f-11e7-8404-1e209a51c5c0.png)

**Comment by Nadapotata** [comment]
![image](https://user-images.githubusercontent.com/12971527/32576997-9262f214-c4a6-11e7-964d-e4c4d48a631b.png)

**Comment by JohnG-001** [comment]
Completed 11/08/17.
